export const customerType = {
    FETCH_CUSTOMER_REQUEST:"FETCH_CUSTOMER_REQUEST",
    FETCH_CUSTOMER_SUCCESS:"FETCH_CUSTOMER_SUCCESS",
    FETCH_CUSTOMER_FAILURE:"FETCH_CUSTOMER_FAILURE",

    RESET_CUSTOMER :"RESET_CUSTOMER",

    ADD_CUSTOMER_STARTED:"ADD_CUSTOMER_STARTED",
    ADD_CUSTOMER_SUCCESS:"ADD_CUSTOMER_SUCCESS",
    ADD_CUSTOMER_FAILURE:"ADD_CUSTOMER_FAILURE"
}