export const storeType = {
    FETCH_STORE_REQUEST:"FETCH_STORE_REQUEST",
    FETCH_STORE_SUCCESS:"FETCH_STORE_SUCCESS",
    FETCH_STORE_FAILURE:"FETCH_STORE_FAILURE",

    FETCH_PRODUCT_REQUEST:"FETCH_PRODUCT_REQUEST",
    FETCH_PRODUCT_SUCCESS:"FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_FAILURE:"FETCH_PRODUCT_FAILURE",

    RESET_PRODUCT:'RESET_PRODUCT',

    ADD_TO_CART:'ADD_TO_CART',
    UPDATE_PRODUCT_FROM_CART:'UPDATE_PRODUCT_FROM_CART',
    REMOVE_FROM_CART:'REMOVE_FROM_CART',
    RESET_CART:"RESET_CART",

    FETCH_CATEGORY_REQUEST:'FETCH_CATEGORY_REQUEST',
    FETCH_CATEGORY_SUCCESS:'FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILURE:'FETCH_CATEGORY_FAILURE'
}